set_property PACKAGE_PIN W7 [get_ports {leds_p[3]}]
set_property PACKAGE_PIN W6 [get_ports {leds_p[2]}]
set_property PACKAGE_PIN W5 [get_ports {leds_p[1]}]
set_property PACKAGE_PIN U7 [get_ports {leds_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_p[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_p[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_p[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_p[0]}]
